# Based on workflow provided here: https://github.com/codacy/codacy-analysis-cli-action

name: Codacy Analysis CLI

on: ["push"]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          echo "$PWD/bin" >> $GITHUB_PATH
          trivy --version

      - name: Run Trivy to generate CycloneDX report
        run: |
          trivy fs --format cyclonedx --output results.cdx /src

      - name: Print CycloneDX output
        run: cat results.cdx

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
            project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}