name: Deploy to EC2

on:
  push:
    branches:
      - main
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./backend"
          target: "/home/ubuntu/cpen321-FoodTrip"

      - name: Rebuild and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/cpen321-FoodTrip/backend
            
            # Write secrets in .env
            cat > .env <<EOF
            PORT=${{ secrets.PROD_PORT }}
            DB_URI=${{ secrets.PROD_DB_URI }}
            EDAMAM_APP_ID=${{ secrets.EDAMAM_APP_ID }}
            EDAMAM_API_KEY=${{ secrets.EDAMAM_API_KEY }}
            EOF

            # Give .env permissions
            chmod 600 .env

            # Build and run container
            docker-compose down
            docker-compose --env-file .env build
            docker-compose --env-file .env up -d
