name: Test Backend

on:
  workflow_run:
    # wait for deploy to complete before running tests 
    # (since non-functional requirement tests may conflict with deploy)
    workflows: ["Deploy to EC2"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Run Jest tests with coverage
        working-directory: backend
        # run non-functional requirement tests separately
        run: npm run test:coverage -- --testPathIgnorePatterns="(/non_functional_requirements/)"
        env:
          EDAMAM_APP_ID: ${{ secrets.EDAMAM_APP_ID }}
          EDAMAM_API_KEY: ${{ secrets.EDAMAM_API_KEY }}
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Run non-functional requirements tests
        working-directory: backend
        run: npm run test -- --testPathPattern="(/non_functional_requirements/)"
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          GATEWAY_BASE_URL: ${{ secrets.GATEWAY_BASE_URL }}

      - name: Upload coverage report
        if: always() # always upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: backend/coverage
