name: Test Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    needs: deploy # ensure deploy job runs first

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Run Jest tests with coverage
        working-directory: backend
        run: npm run test:coverage
        env:
          EDAMAM_APP_ID: ${{ secrets.EDAMAM_APP_ID }}
          EDAMAM_API_KEY: ${{ secrets.EDAMAM_API_KEY }}
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          GATEWAY_BASE_URL: ${{ secrets.GATEWAY_BASE_URL }}

      - name: Upload coverage report
        if: always() # always upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: backend/coverage
